<?php

// $list_article sera ma variable contenant mon tableau. Se sera aussi un tableau associatif, clé/valeur.
$list_articles = array();

$list_articles['__404__'] = [

    'title'    => 'Un article qui ne devrais pas exister',
    'author'   => 'Edward Nigma',
    'text'     => '<p style="color: red; font-weight: bold;">
                     Votre article n\'existe pas !!
                   </p>',
    'category' => 'ERROR 404',
    'publish'  => date('D d M Y'),
    'image'    => 'riddler-edward-nigma-mad-6.39.jpg'
  
];

// j'ajoute dans le tableau $list_articles à la clé ['artcile_1'] un tableau associatif, qui sera la valeur de cette clé.
// 'article_1', correspond à l'identifiant(ID) de l'article.
$list_articles['article_1'] = [

    'title'    => 'Lorem ipsum dolor sit amet',
    'author'   => 'John Marchill',
    'text'     => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A quaerat commodi architecto perferendis sit sed ipsa excepturi repellendus accusamus iure, ipsam quos esse iste consectetur nam dolore minima eum obcaecati libero officiis quisquam quo? Ab, magni nostrum! Quia, laborum ad. Dolorem quidem, modi odit saepe enim perferendis, dolorum dolore hic illum accusamus nesciunt eos animi culpa tempora numquam, veniam rerum? Sapiente officia fugit quos eligendi tempore modi, dolore consequuntur vel tempora inventore culpa saepe eius, aperiam est quo? Nostrum aliquid dicta veniam ratione! Quis, possimus distinctio non expedita praesentium incidunt sunt voluptatum, eius omnis perferendis commodi voluptate quisquam. Harum consequatur consequuntur sint et, accusamus illo, autem voluptate aliquam at adipisci ut exercitationem repellat a perspiciatis commodi necessitatibus sit odit? Nisi aut sapiente repudiandae cum aliquid asperiores pariatur quibusdam libero, reprehenderit quisquam illo quaerat porro, veniam, atque temporibus laboriosam quidem consectetur ex sunt. Ratione minima eveniet, vel similique magnam ex totam.</p>
                   <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Impedit doloribus necessitatibus eveniet et blanditiis deleniti velit laboriosam fugiat quasi atque, error a quibusdam quaerat eos distinctio illum. Maiores commodi a numquam placeat enim iste, facilis, illo rerum at officiis sequi, saepe nisi impedit distinctio exercitationem ut dignissimos asperiores. Sunt vitae vel, eveniet atque magnam rem, natus consequuntur eum quidem quasi nemo est maiores consectetur iure ipsam necessitatibus beatae fugiat similique officiis esse adipisci! Saepe, ex. Id dolor fuga aperiam, tempore ut earum eius vero, numquam mollitia labore pariatur voluptatum. Delectus, laborum natus. Quaerat, nihil excepturi libero esse unde fuga vero veniam molestias cum rem nostrum nemo, laboriosam, fugiat vitae enim consequuntur fugit nisi. Dolor veritatis modi exercitationem nesciunt quia placeat, at fuga ratione nisi unde sequi, ullam facere quisquam minus natus id accusamus a architecto impedit similique odio possimus fugit quasi inventore. Omnis quibusdam reiciendis doloremque fugit asperiores harum recusandae tempore repellendus nesciunt eligendi quis officiis molestias ipsam mollitia, alias architecto ipsa, iusto porro consectetur officia reprehenderit sed saepe sapiente inventore! Corrupti neque cupiditate facere beatae iusto iure in suscipit dolore explicabo numquam aut, accusantium molestiae tenetur corporis dolorum est, consectetur ducimus, ab atque! Atque dolores consequatur perspiciatis aliquam nemo!</p>
                   <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Animi facere perspiciatis at corrupti quam impedit quasi accusantium porro magnam suscipit officiis voluptatum autem velit eveniet laudantium, consectetur reprehenderit ut beatae sint labore expedita! Natus mollitia dolores ipsum, quasi unde doloremque porro delectus sapiente est numquam voluptatibus, maiores voluptates excepturi, repellat quas adipisci commodi! Mollitia maiores accusamus vel eius? Ad, culpa hic obcaecati officia, natus soluta harum asperiores a esse ex praesentium laudantium consequatur quas. Veniam.</p>',
    'category' => 'team',
    'publish'  => 'le 27 mars 2018',
    'image'    => 'icon-dar.png'
  
];

// j'ajoute dans le tableau $list_articles à la clé ['artcile_2'] un tableau associatif, qui sera la valeur de cette clé.
// 'article_2', correspond à l'identifiant(ID) de l'article.
$list_articles['article_2'] = [

    'title'    => 'Lorem ipsum dolor sit amet',
    'author'   => 'John Marchill',
    'text'     => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A quaerat commodi architecto perferendis sit sed ipsa excepturi repellendus accusamus iure, ipsam quos esse iste consectetur nam dolore minima eum obcaecati libero officiis quisquam quo? Ab, magni nostrum! Quia, laborum ad. Dolorem quidem, modi odit saepe enim perferendis, dolorum dolore hic illum accusamus nesciunt eos animi culpa tempora numquam, veniam rerum? Sapiente officia fugit quos eligendi tempore modi, dolore consequuntur vel tempora inventore culpa saepe eius, aperiam est quo? Nostrum aliquid dicta veniam ratione! Quis, possimus distinctio non expedita praesentium incidunt sunt voluptatum, eius omnis perferendis commodi voluptate quisquam. Harum consequatur consequuntur sint et, accusamus illo, autem voluptate aliquam at adipisci ut exercitationem repellat a perspiciatis commodi necessitatibus sit odit? Nisi aut sapiente repudiandae cum aliquid asperiores pariatur quibusdam libero, reprehenderit quisquam illo quaerat porro, veniam, atque temporibus laboriosam quidem consectetur ex sunt. Ratione minima eveniet, vel similique magnam ex totam.</p>
                   <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Impedit doloribus necessitatibus eveniet et blanditiis deleniti velit laboriosam fugiat quasi atque, error a quibusdam quaerat eos distinctio illum. Maiores commodi a numquam placeat enim iste, facilis, illo rerum at officiis sequi, saepe nisi impedit distinctio exercitationem ut dignissimos asperiores. Sunt vitae vel, eveniet atque magnam rem, natus consequuntur eum quidem quasi nemo est maiores consectetur iure ipsam necessitatibus beatae fugiat similique officiis esse adipisci! Saepe, ex. Id dolor fuga aperiam, tempore ut earum eius vero, numquam mollitia labore pariatur voluptatum. Delectus, laborum natus. Quaerat, nihil excepturi libero esse unde fuga vero veniam molestias cum rem nostrum nemo, laboriosam, fugiat vitae enim consequuntur fugit nisi. Dolor veritatis modi exercitationem nesciunt quia placeat, at fuga ratione nisi unde sequi, ullam facere quisquam minus natus id accusamus a architecto impedit similique odio possimus fugit quasi inventore. Omnis quibusdam reiciendis doloremque fugit asperiores harum recusandae tempore repellendus nesciunt eligendi quis officiis molestias ipsam mollitia, alias architecto ipsa, iusto porro consectetur officia reprehenderit sed saepe sapiente inventore! Corrupti neque cupiditate facere beatae iusto iure in suscipit dolore explicabo numquam aut, accusantium molestiae tenetur corporis dolorum est, consectetur ducimus, ab atque! Atque dolores consequatur perspiciatis aliquam nemo!</p>
                   <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Animi facere perspiciatis at corrupti quam impedit quasi accusantium porro magnam suscipit officiis voluptatum autem velit eveniet laudantium, consectetur reprehenderit ut beatae sint labore expedita! Natus mollitia dolores ipsum, quasi unde doloremque porro delectus sapiente est numquam voluptatibus, maiores voluptates excepturi, repellat quas adipisci commodi! Mollitia maiores accusamus vel eius? Ad, culpa hic obcaecati officia, natus soluta harum asperiores a esse ex praesentium laudantium consequatur quas. Veniam.</p>',
    'category' => 'news',
    'publish'  => 'le 27 mars 2018',
    'image'    => 'icon-john.png'
  
];

$list_articles['article_3'] = [

    'title'    => 'Lorem ipsum dolor sit amet',
    'author'   => 'John Marchill',
    'text'     => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A quaerat commodi architecto perferendis sit sed ipsa excepturi repellendus accusamus iure, ipsam quos esse iste consectetur nam dolore minima eum obcaecati libero officiis quisquam quo? Ab, magni nostrum! Quia, laborum ad. Dolorem quidem, modi odit saepe enim perferendis, dolorum dolore hic illum accusamus nesciunt eos animi culpa tempora numquam, veniam rerum? Sapiente officia fugit quos eligendi tempore modi, dolore consequuntur vel tempora inventore culpa saepe eius, aperiam est quo? Nostrum aliquid dicta veniam ratione! Quis, possimus distinctio non expedita praesentium incidunt sunt voluptatum, eius omnis perferendis commodi voluptate quisquam. Harum consequatur consequuntur sint et, accusamus illo, autem voluptate aliquam at adipisci ut exercitationem repellat a perspiciatis commodi necessitatibus sit odit? Nisi aut sapiente repudiandae cum aliquid asperiores pariatur quibusdam libero, reprehenderit quisquam illo quaerat porro, veniam, atque temporibus laboriosam quidem consectetur ex sunt. Ratione minima eveniet, vel similique magnam ex totam.</p>
                   <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Impedit doloribus necessitatibus eveniet et blanditiis deleniti velit laboriosam fugiat quasi atque, error a quibusdam quaerat eos distinctio illum. Maiores commodi a numquam placeat enim iste, facilis, illo rerum at officiis sequi, saepe nisi impedit distinctio exercitationem ut dignissimos asperiores. Sunt vitae vel, eveniet atque magnam rem, natus consequuntur eum quidem quasi nemo est maiores consectetur iure ipsam necessitatibus beatae fugiat similique officiis esse adipisci! Saepe, ex. Id dolor fuga aperiam, tempore ut earum eius vero, numquam mollitia labore pariatur voluptatum. Delectus, laborum natus. Quaerat, nihil excepturi libero esse unde fuga vero veniam molestias cum rem nostrum nemo, laboriosam, fugiat vitae enim consequuntur fugit nisi. Dolor veritatis modi exercitationem nesciunt quia placeat, at fuga ratione nisi unde sequi, ullam facere quisquam minus natus id accusamus a architecto impedit similique odio possimus fugit quasi inventore. Omnis quibusdam reiciendis doloremque fugit asperiores harum recusandae tempore repellendus nesciunt eligendi quis officiis molestias ipsam mollitia, alias architecto ipsa, iusto porro consectetur officia reprehenderit sed saepe sapiente inventore! Corrupti neque cupiditate facere beatae iusto iure in suscipit dolore explicabo numquam aut, accusantium molestiae tenetur corporis dolorum est, consectetur ducimus, ab atque! Atque dolores consequatur perspiciatis aliquam nemo!</p>
                   <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Animi facere perspiciatis at corrupti quam impedit quasi accusantium porro magnam suscipit officiis voluptatum autem velit eveniet laudantium, consectetur reprehenderit ut beatae sint labore expedita! Natus mollitia dolores ipsum, quasi unde doloremque porro delectus sapiente est numquam voluptatibus, maiores voluptates excepturi, repellat quas adipisci commodi! Mollitia maiores accusamus vel eius? Ad, culpa hic obcaecati officia, natus soluta harum asperiores a esse ex praesentium laudantium consequatur quas. Veniam.</p>',
    'category' => 'news',
    'publish'  => 'le 27 mars 2018',
    'image'    => 'icon-ohz.png'
  
];

$list_articles['article_4'] = [

    'title'    => 'Lorem ipsum dolor sit amet',
    'author'   => 'John Marchill',
    'text'     => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A quaerat commodi architecto perferendis sit sed ipsa excepturi repellendus accusamus iure, ipsam quos esse iste consectetur nam dolore minima eum obcaecati libero officiis quisquam quo? Ab, magni nostrum! Quia, laborum ad. Dolorem quidem, modi odit saepe enim perferendis, dolorum dolore hic illum accusamus nesciunt eos animi culpa tempora numquam, veniam rerum? Sapiente officia fugit quos eligendi tempore modi, dolore consequuntur vel tempora inventore culpa saepe eius, aperiam est quo? Nostrum aliquid dicta veniam ratione! Quis, possimus distinctio non expedita praesentium incidunt sunt voluptatum, eius omnis perferendis commodi voluptate quisquam. Harum consequatur consequuntur sint et, accusamus illo, autem voluptate aliquam at adipisci ut exercitationem repellat a perspiciatis commodi necessitatibus sit odit? Nisi aut sapiente repudiandae cum aliquid asperiores pariatur quibusdam libero, reprehenderit quisquam illo quaerat porro, veniam, atque temporibus laboriosam quidem consectetur ex sunt. Ratione minima eveniet, vel similique magnam ex totam.</p>
                   <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Impedit doloribus necessitatibus eveniet et blanditiis deleniti velit laboriosam fugiat quasi atque, error a quibusdam quaerat eos distinctio illum. Maiores commodi a numquam placeat enim iste, facilis, illo rerum at officiis sequi, saepe nisi impedit distinctio exercitationem ut dignissimos asperiores. Sunt vitae vel, eveniet atque magnam rem, natus consequuntur eum quidem quasi nemo est maiores consectetur iure ipsam necessitatibus beatae fugiat similique officiis esse adipisci! Saepe, ex. Id dolor fuga aperiam, tempore ut earum eius vero, numquam mollitia labore pariatur voluptatum. Delectus, laborum natus. Quaerat, nihil excepturi libero esse unde fuga vero veniam molestias cum rem nostrum nemo, laboriosam, fugiat vitae enim consequuntur fugit nisi. Dolor veritatis modi exercitationem nesciunt quia placeat, at fuga ratione nisi unde sequi, ullam facere quisquam minus natus id accusamus a architecto impedit similique odio possimus fugit quasi inventore. Omnis quibusdam reiciendis doloremque fugit asperiores harum recusandae tempore repellendus nesciunt eligendi quis officiis molestias ipsam mollitia, alias architecto ipsa, iusto porro consectetur officia reprehenderit sed saepe sapiente inventore! Corrupti neque cupiditate facere beatae iusto iure in suscipit dolore explicabo numquam aut, accusantium molestiae tenetur corporis dolorum est, consectetur ducimus, ab atque! Atque dolores consequatur perspiciatis aliquam nemo!</p>
                   <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Animi facere perspiciatis at corrupti quam impedit quasi accusantium porro magnam suscipit officiis voluptatum autem velit eveniet laudantium, consectetur reprehenderit ut beatae sint labore expedita! Natus mollitia dolores ipsum, quasi unde doloremque porro delectus sapiente est numquam voluptatibus, maiores voluptates excepturi, repellat quas adipisci commodi! Mollitia maiores accusamus vel eius? Ad, culpa hic obcaecati officia, natus soluta harum asperiores a esse ex praesentium laudantium consequatur quas. Veniam.</p>',
    'category' => 'work',
    'publish'  => 'le 27 mars 2018',
    'image'    => 'icon-spr.png'
  
];

$list_articles['article_5'] = [

    'title'    => 'Lorem ipsum dolor sit amet',
    'author'   => 'John Marchill',
    'text'     => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A quaerat commodi architecto perferendis sit sed ipsa excepturi repellendus accusamus iure, ipsam quos esse iste consectetur nam dolore minima eum obcaecati libero officiis quisquam quo? Ab, magni nostrum! Quia, laborum ad. Dolorem quidem, modi odit saepe enim perferendis, dolorum dolore hic illum accusamus nesciunt eos animi culpa tempora numquam, veniam rerum? Sapiente officia fugit quos eligendi tempore modi, dolore consequuntur vel tempora inventore culpa saepe eius, aperiam est quo? Nostrum aliquid dicta veniam ratione! Quis, possimus distinctio non expedita praesentium incidunt sunt voluptatum, eius omnis perferendis commodi voluptate quisquam. Harum consequatur consequuntur sint et, accusamus illo, autem voluptate aliquam at adipisci ut exercitationem repellat a perspiciatis commodi necessitatibus sit odit? Nisi aut sapiente repudiandae cum aliquid asperiores pariatur quibusdam libero, reprehenderit quisquam illo quaerat porro, veniam, atque temporibus laboriosam quidem consectetur ex sunt. Ratione minima eveniet, vel similique magnam ex totam.</p>
                   <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Impedit doloribus necessitatibus eveniet et blanditiis deleniti velit laboriosam fugiat quasi atque, error a quibusdam quaerat eos distinctio illum. Maiores commodi a numquam placeat enim iste, facilis, illo rerum at officiis sequi, saepe nisi impedit distinctio exercitationem ut dignissimos asperiores. Sunt vitae vel, eveniet atque magnam rem, natus consequuntur eum quidem quasi nemo est maiores consectetur iure ipsam necessitatibus beatae fugiat similique officiis esse adipisci! Saepe, ex. Id dolor fuga aperiam, tempore ut earum eius vero, numquam mollitia labore pariatur voluptatum. Delectus, laborum natus. Quaerat, nihil excepturi libero esse unde fuga vero veniam molestias cum rem nostrum nemo, laboriosam, fugiat vitae enim consequuntur fugit nisi. Dolor veritatis modi exercitationem nesciunt quia placeat, at fuga ratione nisi unde sequi, ullam facere quisquam minus natus id accusamus a architecto impedit similique odio possimus fugit quasi inventore. Omnis quibusdam reiciendis doloremque fugit asperiores harum recusandae tempore repellendus nesciunt eligendi quis officiis molestias ipsam mollitia, alias architecto ipsa, iusto porro consectetur officia reprehenderit sed saepe sapiente inventore! Corrupti neque cupiditate facere beatae iusto iure in suscipit dolore explicabo numquam aut, accusantium molestiae tenetur corporis dolorum est, consectetur ducimus, ab atque! Atque dolores consequatur perspiciatis aliquam nemo!</p>
                   <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Animi facere perspiciatis at corrupti quam impedit quasi accusantium porro magnam suscipit officiis voluptatum autem velit eveniet laudantium, consectetur reprehenderit ut beatae sint labore expedita! Natus mollitia dolores ipsum, quasi unde doloremque porro delectus sapiente est numquam voluptatibus, maiores voluptates excepturi, repellat quas adipisci commodi! Mollitia maiores accusamus vel eius? Ad, culpa hic obcaecati officia, natus soluta harum asperiores a esse ex praesentium laudantium consequatur quas. Veniam.</p>',
    'category' => 'team',
    'publish'  => 'le 27 mars 2018',
    'image'    => 'icon-tr.png'
  
];

$list_articles['article_6'] = [

    'title'    => 'Lorem ipsum dolor sit amet',
    'author'   => 'John Marchill',
    'text'     => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A quaerat commodi architecto perferendis sit sed ipsa excepturi repellendus accusamus iure, ipsam quos esse iste consectetur nam dolore minima eum obcaecati libero officiis quisquam quo? Ab, magni nostrum! Quia, laborum ad. Dolorem quidem, modi odit saepe enim perferendis, dolorum dolore hic illum accusamus nesciunt eos animi culpa tempora numquam, veniam rerum? Sapiente officia fugit quos eligendi tempore modi, dolore consequuntur vel tempora inventore culpa saepe eius, aperiam est quo? Nostrum aliquid dicta veniam ratione! Quis, possimus distinctio non expedita praesentium incidunt sunt voluptatum, eius omnis perferendis commodi voluptate quisquam. Harum consequatur consequuntur sint et, accusamus illo, autem voluptate aliquam at adipisci ut exercitationem repellat a perspiciatis commodi necessitatibus sit odit? Nisi aut sapiente repudiandae cum aliquid asperiores pariatur quibusdam libero, reprehenderit quisquam illo quaerat porro, veniam, atque temporibus laboriosam quidem consectetur ex sunt. Ratione minima eveniet, vel similique magnam ex totam.</p>
                   <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Impedit doloribus necessitatibus eveniet et blanditiis deleniti velit laboriosam fugiat quasi atque, error a quibusdam quaerat eos distinctio illum. Maiores commodi a numquam placeat enim iste, facilis, illo rerum at officiis sequi, saepe nisi impedit distinctio exercitationem ut dignissimos asperiores. Sunt vitae vel, eveniet atque magnam rem, natus consequuntur eum quidem quasi nemo est maiores consectetur iure ipsam necessitatibus beatae fugiat similique officiis esse adipisci! Saepe, ex. Id dolor fuga aperiam, tempore ut earum eius vero, numquam mollitia labore pariatur voluptatum. Delectus, laborum natus. Quaerat, nihil excepturi libero esse unde fuga vero veniam molestias cum rem nostrum nemo, laboriosam, fugiat vitae enim consequuntur fugit nisi. Dolor veritatis modi exercitationem nesciunt quia placeat, at fuga ratione nisi unde sequi, ullam facere quisquam minus natus id accusamus a architecto impedit similique odio possimus fugit quasi inventore. Omnis quibusdam reiciendis doloremque fugit asperiores harum recusandae tempore repellendus nesciunt eligendi quis officiis molestias ipsam mollitia, alias architecto ipsa, iusto porro consectetur officia reprehenderit sed saepe sapiente inventore! Corrupti neque cupiditate facere beatae iusto iure in suscipit dolore explicabo numquam aut, accusantium molestiae tenetur corporis dolorum est, consectetur ducimus, ab atque! Atque dolores consequatur perspiciatis aliquam nemo!</p>
                   <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Animi facere perspiciatis at corrupti quam impedit quasi accusantium porro magnam suscipit officiis voluptatum autem velit eveniet laudantium, consectetur reprehenderit ut beatae sint labore expedita! Natus mollitia dolores ipsum, quasi unde doloremque porro delectus sapiente est numquam voluptatibus, maiores voluptates excepturi, repellat quas adipisci commodi! Mollitia maiores accusamus vel eius? Ad, culpa hic obcaecati officia, natus soluta harum asperiores a esse ex praesentium laudantium consequatur quas. Veniam.</p>',
    'category' => 'work',
    'publish'  => 'le 27 mars 2018',
    'image'    => 'icon-tre.png'
  
];